### ISSUE TITLE
Official Multiboot ROMs don't work

### ISSUE THREAD

**Issue by RosalinaFan573** [FIX94/gba-link-cable-rom-sender#1]
I tried to use this tool with all of my official multiboot ROMs, but they only give me a white screen. What am I doing wrong?

**Comment by FIX94** [comment]
what are "official" multiboot roms exactly, and what goes wrong? gotta go into more details like what titles exactly and whats happening.

**Comment by RosalinaFan573** [comment]
I have tried many multiboot ROMs I have extracted from GameCube discs (that work perfectly fine in an emulator) and they send to the GBA, but when it finishes sending, the GBA gets a white screen.

**Comment by FIX94** [comment]
from which discs exactly? and which emus were tested? come on, you gotta be more specific than that if you want any actual help

**Comment by RosalinaFan573** [comment]
I tested all ROMs using VBA-M, and the ROMs were ripped from Pokemon Colosseum Bonus Disc, Nintendo GameCube Preview Disc and Nintendo Puzzle Collection.

**Comment by FIX94** [comment]
So I did have the puzzle collection to check and I found out what was going on there thanks to a .elf version with named functions, added an automatic patcher for that type of file to boot up. Probably other types of official roms may have other types of patches required to make them work, I did not understand the layout of the pokemon colloseum bonus disc and I dont have that preview file here to check it out, you'll have to see I guess.

**Comment by RosalinaFan573** [comment]
They work now! Only problem is that you accidentally packaged the v1.0 version of the Wii version in the v1.1 ZIP.

**Comment by FIX94** [comment]
it says v1.1 here and works fine though, you sure you properly replaced your file to test that?
